package br.com.modelo;
// Generated 28/06/2015 17:58:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer id;
     private String descricao;
     private String palavrasChaves;
     private Set<Tweet> tweets = new HashSet<Tweet>(0);

    public Categoria() {
    }

	
    public Categoria(String descricao) {
        this.descricao = descricao;
    }
    public Categoria(String descricao, String palavrasChaves, Set<Tweet> tweets) {
       this.descricao = descricao;
       this.palavrasChaves = palavrasChaves;
       this.tweets = tweets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getPalavrasChaves() {
        return this.palavrasChaves;
    }
    
    public void setPalavrasChaves(String palavrasChaves) {
        this.palavrasChaves = palavrasChaves;
    }
    public Set<Tweet> getTweets() {
        return this.tweets;
    }
    
    public void setTweets(Set<Tweet> tweets) {
        this.tweets = tweets;
    }




}


