package br.com.modelo;
// Generated 28/06/2015 17:58:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Localizacao generated by hbm2java
 */
public class Localizacao  implements java.io.Serializable {


     private Integer id;
     private String descricao;
     private String palavrasChaves;
     private String longitude;
     private String latitude;
     private Set<Tweet> tweets = new HashSet<Tweet>(0);

    public Localizacao() {
    }

	
    public Localizacao(String descricao) {
        this.descricao = descricao;
    }
    public Localizacao(String descricao, String palavrasChaves, String longitude, String latitude, Set<Tweet> tweets) {
       this.descricao = descricao;
       this.palavrasChaves = palavrasChaves;
       this.longitude = longitude;
       this.latitude = latitude;
       this.tweets = tweets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getPalavrasChaves() {
        return this.palavrasChaves;
    }
    
    public void setPalavrasChaves(String palavrasChaves) {
        this.palavrasChaves = palavrasChaves;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
    public Set<Tweet> getTweets() {
        return this.tweets;
    }
    
    public void setTweets(Set<Tweet> tweets) {
        this.tweets = tweets;
    }




}


